default: setMods/MultiSetApp.java setMods/ArraySet.java setMods/ListSet.java setMods/ISet.java
	javac setMods/MultiSetApp.java setMods/ArraySet.java setMods/ListSet.java setMods/ISet.java

run: setMods/MultiSetApp.class setMods/ArraySet.class setMods/ListSet.class setMods/ISet.class
	java setMods.MultiSetApp

clean:
	rm -f setMods/*.class
