default: cpsc2150/banking/MortgageApp.java cpsc2150/banking/IMortgageController.java cpsc2150/banking/MortgageController.java cpsc2150/banking/MortgageView.java cpsc2150/banking/IMortgageView.java
	javac cpsc2150/banking/MortgageApp.java cpsc2150/banking/IMortgageController.java cpsc2150/banking/MortgageController.java cpsc2150/banking/MortgageView.java cpsc2150/banking/IMortgageView.java
	
run: cpsc2150/banking/MortgageApp.class cpsc2150/banking/IMortgageController.class cpsc2150/banking/MortgageController.class cpsc2150/banking/MortgageView.class cpsc2150/banking/IMortgageView.class
	java cpsc2150.banking.MortgageApp

clean:
	rm -f cpsc2150/banking/*.class
